WizardName = 'Bromedius'
print('Welcome, welcome. I am ' + WizardName + '.')
print('What is your name, friend, and fellow traveler? ')
print()
Usern = input()
print()
print(Usern + "... what kind of imbecile has a name like that? ")
print()
Culture = input()
print() 
print (Culture + '?! ' + Culture + "!! I can't believe you even remember that long extinct culture! *laughs* Ah, you sure have a natural joketeller in you...") 
print("What do you reckon? What do you think your favorite hobby is?")
print()
FavoriteHobby = input()
print()
print("[Insert Ridiculous Thing Here]")